### ISSUE TITLE
아이디 인덱싱 배열 문제

### ISSUE THREAD

**Issue by ggs134** [Onther-Tech/HOneChain-OneId#1]
https://github.com/Onther-Tech/honechain-oneid/blob/master/contracts/Honechain_OneId.sol#L32

    bytes32[] public oneIdAll; //전체 One ID
    bytes32[] public extUserIdAll; //전체 사용자ID

이 두 변수는 

getOneIdAll(), getExtUserIdAll () 두 함수를 호출하는 과정에서 전체 원아이디와 사용자아이디를 인덱싱 하는 방식으로 사용되는 것으로 보임.

단순 인덱싱이 목적이라면 가스비 5000 이상을 쓰는 배열에 그 값들을 저장한다는게 낭비로 보여짐.

원아이디 생성간 event를 일으켜 로그에 쌓으니, 향후 web3의 
로그 조회 기능을 이용해서
reciept에서 불러온 데이터를 바탕으로 인덱싱 하는것이 올바른 구조로 보임

https://web3js.readthedocs.io/en/1.0/web3-eth.html?highlight=logs#getpastlogs

**Comment by thomashin** [comment]
OneId.sol로 이전
